### ISSUE TITLE
mariadb-slave replication on different host

### ISSUE THREAD

**Issue by nitic** [yidigun/mariadb-replication#1]
Please guide me how to setup mariadb-slave replication on different host. 

thank you.

**Comment by dagui0** [comment]
Sorry I did not realize this issue for days. Did you solve your problems?
What is your problems? Let me know more details.

**Comment by dagui0** [comment]
There are bugs on version 11 image, because from v11 mysql* commands are changed to mariadb*. So I fix scripts. Please try once more, and tell me if you encounter more troubles.

To try new docker image, be sure to delete old images.

```
docker rmi yidigun/mariadb-replication:11
or
docker rmi yidigun/mariadb-replication:latest
```
